### ISSUE TITLE
hold and delete function not working

### ISSUE THREAD

**Issue by GosuCode** [ask-org/pomo-timer#9]
hold and delete function not working,
When holding the task, the task should be deleted.

**Comment by gmottajr** [comment]
Shall I help you out with that? Please let me know which function is the one supposed to be fixed and assign this issue to me.
Thank you very much!

**Comment by adarshkunwar** [comment]
hi @gmottajr  could you look into issue 2? we are new with the open source and dont really have much experience with it as of yet.

**Comment by gmottajr** [comment]
Sure, I'll take a look.
Thanks for your response.

**Comment by adarshkunwar** [comment]
The function has been changed to slide to delete.
